name: test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  unit:
    name: unit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.20' # The Go version to download (if necessary) and use.
      - name: Test
        env:
          USERNAME: ${{ secrets.USERNAME }}
          SECRET: ${{ secrets.SECRET }}
        run: go test -v ./...